Repository labseu2-niyon/backend, pull requests merged in 2019-09, with the labels that each got.

#44 Feature/autocomplete
  .eslintrc.js
  .gitignore
  __test__/autocomplete.test.js
  __test__/index.test.js
  api/controllers/autocomplete.js
  api/index.js
  api/routes/autocomplete.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#64 Ft/create connections and chat tables
  database/migrations/20190913092246-create-connections.js
  database/migrations/20190913095930-create-chats.js
  database/models/chats.js
  database/models/connections.js
  database/models/users.js
  package.json
Labels: enhancement

#68 Bug/image upload
  api/chats/chat.js
  config/cloudinary.js
  index.js
  package-lock.json
  package.json
  server.js
Labels: bug

#66 created socket connection
  __test__/chats.js
  api/chats/chat.js
  api/controllers/user.js
  database/migrations/20190913092246-create-connections.js
  database/migrations/20190913095930-create-chats.js
  database/models/chats.js
  database/models/connections.js
  database/models/users.js
  database/seeders/20190916094752-demo-connections.js
  database/seeders/20190917075005-demo-chats.js
  package.json
Labels: enhancement, work in progress

#72 Ft/chats
  __test__/chats.js
  api/chats/chat.js
  package.json
Labels: enhancement, work in progress

#80 Add Validation to Connection Endpoints
  api/controllers/connection.js
  api/helpers/jwt.js
  api/routes/connectionRoute.js
  package.json
Labels: enhancement

#82 Added Redirect url for registered users
  api/controllers/auth.js
Labels: work in progress
